export const CATEGORY_COLORS: Record<string, { bg: string; text: string; dot: string }> = {
  preventive:      { bg: "bg-green-50",    text: "text-green-700",      dot: "#22c55e" },
  urological:      { bg: "bg-blue-50",     text: "text-blue-700",       dot: "#3b82f6" },
  emergency:       { bg: "bg-red-50",      text: "text-red-700",        dot: "#ef4444" },
  admin:           { bg: "bg-gray-50",     text: "text-gray-600",       dot: "#94a3b8" },
  gi:              { bg: "bg-orange-50",   text: "text-orange-700",     dot: "#f97316" },
  dermatology:     { bg: "bg-pink-50",     text: "text-pink-700",       dot: "#f472b6" },
  reproductive:    { bg: "bg-purple-50",   text: "text-purple-700",     dot: "#a855f7" },
  dental:          { bg: "bg-cyan-50",     text: "text-cyan-700",       dot: "#06b6d4" },
  ophthalmology:   { bg: "bg-teal-50",     text: "text-teal-700",       dot: "#14b8a6" },
  musculoskeletal: { bg: "bg-indigo-50",   text: "text-indigo-700",     dot: "#6366f1" },
  cardiology:      { bg: "bg-red-100",     text: "text-red-800",        dot: "#dc2626" },
  neurology:       { bg: "bg-violet-50",   text: "text-violet-700",     dot: "#7c3aed" },
  respiratory:     { bg: "bg-sky-50",      text: "text-sky-700",        dot: "#38bdf8" },
  oncology:        { bg: "bg-orange-100",  text: "text-orange-800",     dot: "#ea580c" },
  general:         { bg: "bg-stone-50",    text: "text-stone-600",      dot: "#78716c" },
};

export const CATEGORY_LABELS: Record<string, string> = {
  preventive:      "Профилактика",
  urological:      "Урология",
  emergency:       "Экстренные",
  admin:           "Администрирование",
  gi:              "ЖКТ",
  dermatology:     "Дерматология",
  reproductive:    "Репродукция",
  dental:          "Стоматология",
  ophthalmology:   "Офтальмология",
  musculoskeletal: "Опорно-двигательная",
  cardiology:      "Кардиология",
  neurology:       "Неврология",
  respiratory:     "Респираторная",
  oncology:        "Онкология",
  general:         "Общее",
};
